"""
Django settings for Renforcement project.

Generated by 'django-admin startproject' using Django 5.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os # os est très essentiel pour récuperer la 
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-#tj89+m_!7q1m#@wp+($s+@gk$t1i_6k74b#v02_gz$#qw36_@'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
# # ALLOWED_HOSTS sert à lister les noms de domaines qui pourrons permettre acceder à mes applications
#  En production les domains peuvent etre 
# ALLOWED_HOSTS = ['mon-site.com', 'www.mon-site.com']

# En developpement les domains peuvent etre 

# ALLOWED_HOSTS = ['127.0.0.1', 'localhost']

ALLOWED_HOSTS = []


# Definitions des applications installées

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth', # cette librairie permet de prendre les views de integré de django
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'Home',
    'Accounts',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Renforcement.urls' 
LOGIN_REDIRECT_URL = 'dashboard'  # Redirige vers la page du tableau de bord après connexion
LOGOUT_REDIRECT_URL = 'login'    # Redirige vers la page de connexion après déconnexion


TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # Ceci permet au reste du sytème de retrouver l'application Templates
        # Pour cela Import os est neccessaire.
'DIRS': [os.path.join(BASE_DIR, 'Home', 'Templates'),  # Pour l'application "Home"
         os.path.join(BASE_DIR, 'Accounts', 'Templates')],  # Pour l'application "Accounts"
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Renforcement.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3', # Cela permet de créer la base de db.sqlite3
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'fr'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'
# Chemin de base pour les fichiers statiques dans mon projet
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
]
# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field
# le model par defaut pour la base de données
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
